openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /github:
    get:
      tags:
        - Github Repository
      summary: Get GitHub Repositories
      description: Retrieve a list of GitHub repositories
      parameters:
        - name: category
          in: query
          description: Filter repositories by category
          schema:
            type: string
            enum: [ NONE, KOTLIN, SELF_HOSTED, OTHER ]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GHRepositoryDao'
  /github/refresh:
    get:
      tags:
        - Github Repository
      summary: Refresh GitHub Repositories
      description: Refresh the list of GitHub repositories
      responses:
        '200':
          description: Refresh successful
        '401':
          description: Unauthorized request
  /github/{id}:
    get:
      tags:
        - Github Repository
      summary: Get GitHub Repository by ID
      description: Retrieve a GitHub repository by its ID
      parameters:
        - name: id
          in: path
          description: ID of the GitHub repository to retrieve
          required: true
          schema:
            type: integer
            default: 3432266
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GHRepositoryDao'
        '404':
          description: Repository not found
  /github/{id}/updateCategory:
    post:
      tags:
        - Github Repository
      summary: Update GitHub Repository Category
      description: Update the category of a GitHub repository
      parameters:
        - name: id
          in: path
          description: ID of the GitHub repository to update
          required: true
          schema:
            type: integer
            default: 3432266
        - name: newCategory
          in: query
          description: New category for the GitHub repository
          schema:
            type: string
            enum: [ NONE, KOTLIN, SELF_HOSTED, OTHER ]
      responses:
        '200':
          description: Category updated successfully
        '404':
          description: Repository not found
        '400':
          description: Invalid category provided
  /github/tags:
    get:
      tags:
        - Tags
      summary: Get Tags
      description: Retrieve a list of tags associated with GitHub repositories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
    put:
      tags:
        - Tags
      summary: Add Tag
      description: Add a new tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '200':
          description: Tag added successfully
        '400':
          description: Bad request
    delete:
      tags:
        - Tags
      summary: Delete Tag
      description: Delete a tag by its name
      parameters:
        - name: tagName
          in: query
          description: Name of the tag to delete
          schema:
            type: string
      responses:
        '200':
          description: Tag deleted successfully
        '404':
          description: Tag not found
  /github/tags/{id}:
    get:
      tags:
        - Tags
      summary: Get Tag by ID
      description: Retrieve a tag by its ID
      parameters:
        - name: id
          in: path
          description: ID of the tag to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '404':
          description: Tag not found
components:
  schemas:
    GHRepositoryDao:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the repository
        name:
          type: string
          description: The name of the repository
        fullName:
          type: string
          description: The full name of the repository
        url:
          type: string
          format: uri
          description: The URL of the repository
        user:
          $ref: '#/components/schemas/GHUser'
        languages:
          type: object
          additionalProperties:
            type: integer
          description: A map of languages used in the repository and their line counts
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: A list of tags associated with the repository
        mainCategory:
          $ref: '#/components/schemas/MainCategory'
          description: The main category of the repository
        license:
          type: string
          description: The license of the repository (optional)
        licenseUrl:
          type: string
          format: uri
          description: The URL to the license of the repository (optional)
        description:
          type: string
          description: A description of the repository (optional)
    GHUser:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the user
        name:
          type: string
          description: The name of the user
        url:
          type: string
          format: uri
          description: The URL of the user's profile
    Tag:
      type: object
      properties:
        name:
          type: string
          description: The name of the tag
        description:
          type: string
          description: The description of the tag
    MainCategory:
      type: string
      enum:
        - NONE
        - KOTLIN
        - SELF_HOSTED
        - OTHER
