kotlin.code.style=official
kotlin.native.cacheKind=none
ksp.useKSP2=true
#Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096m" -XX:+UseParallelGC
org.gradle.parallel=true
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Compose
#MPP
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformation=true
kotlinx.atomicfu.enableJsIrTransformation=true
org.jetbrains.atomicfu.build.scan.enabled=true