DB_URL=jdbc:h2:file:./demodb
DB_DRIVER=org.h2.Driver
DB_USER=
DB_PASSWORD=
auth.digest.alg=SHA-256
auth.digest=TTDTest
auth.password=Test123!
auth.username=test123
auth.session.realm=TTD Realm Test
auth.session.name=takao-session