ktor {
  deployment {
    host = ${SERVER_URL}
    port = 8080
  }
  application {
    modules = [com.takaotech.dashboard.ApplicationKt.mainModule]
  }
}

databases {
  database {
    url = ${DB_URL}
    driver = ${DB_DRIVER}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
  }
  redis {
    url = ${REDIS_URL}
  }
}

github {
  token = ${SERVER_GITHUB_TOKEN}
}

authentication {
  google {
    oauth2 {
      redirect = ${OAUTH_GOOGLE_REDIRECT}
      clientId = ${OAUTH_GOOGLE_CLIENT_ID}
      clientSecret = ${OAUTH_GOOGLE_CLIENT_SECRET}
    }
    jwt {
      issuer = ${JWT_GOOGLE_ISSUER}
      audience = ${JWT_GOOGLE_AUDIENCE}
    }
  }
  ttd {
    tjwt {
      version = ${JWT_TAKAO_VERSION}
      secret = ${JWT_TAKAO_SECRET}
      issuer = ${JWT_TAKAO_ISSUER}
      audience = ${JWT_TAKAO_AUDIENCE}
      realm = ${JWT_TAKAO_REALM}
      accessLifetime = ${JWT_TAKAO_ACCESS_LIFETIME}
      refreshLifetime = ${JWT_TAKAO_REFRESH_LIFETIME}
    }
  }
}