# TTD Env
DB_URL=jdbc:h2:file:./demodb
DB_DRIVER=org.h2.Driver
DB_USER=
DB_PASSWORD=

ENDPOINT_URL=<endpoint of server for app>

SERVER_GITHUB_TOKEN=<Github Token>
OAUTH_GOOGLE_CLIENT_ID=
OAUTH_GOOGLE_CLIENT_SECRET=

AUTH_GOOGLE_CLIENT_ID_ANDROID_WEB=<same AUTH_GOOGLE_CLIENT_ID>
JWT_GOOGLE_ISSUER=https://accounts.google.com
JWT_GOOGLE_AUDIENCE=<public>
JWT_TAKAO_SECRET=
JWT_TAKAO_ISSUER=http://0.0.0.0:8080/
JWT_TAKAO_AUDIENCE=http://0.0.0.0:8080/audience
JWT_TAKAO_REALM=TTD
JWT_TAKAO_ACCESS_LIFETIME=
JWT_TAKAO_REFRESH_LIFETIME=
JWT_TAKAO_VERSION=1