# TTD Env
DB_URL=jdbc:h2:file:./demodb
DB_DRIVER=org.h2.Driver
DB_USER=
DB_PASSWORD=

ENDPOINT_URL=<endpoint of server for app>

SERVER_GITHUB_TOKEN=<Github Token>

AUTH_GOOGLE_CLIENT_ID=
AUTH_GOOGLE_CLIENT_SECRET=

AUTH_GOOGLE_CLIENT_ID_ANDROID_WEB=<same AUTH_GOOGLE_CLIENT_ID>
jwt.google.issuer=https://accounts.google.com
jwt.google.audience=<public>

jwt.takao.secret=
jwt.takao.issuer=http://0.0.0.0:8080/
jwt.takao.audience=http://0.0.0.0:8080/audience
jwt.takao.realm=TTD
jwt.takao.access.lifetime=
jwt.takao.refresh.lifetime=
jwt.takao.version=1