# Usage
#   Start:          docker compose up
#   With helpers:   docker compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker compose down
#   Destroy:        docker compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

name: kotlin-italia
version: "3.8"
services:
  # Comment out everything below this point if you are using an external Postgres database
  db:
    container_name: pg-database
    image: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    ports:
      # Pass down internal port because it's set dynamically by other services
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # PGDATA directory is persisted between restarts
      - ./volumes/db/data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  ttd:
    image: samuele794/ttd:test
    restart: unless-stopped
    ports:
      - "8002:8080"
    environment:
      #DB Credentials
      DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      DB_DRIVER: org.postgresql.Driver
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      #Google Login
      JWT_GOOGLE_ISSUER: https://accounts.google.com
      JWT_GOOGLE_AUDIENCE: ${JWT_GOOGLE_AUDIENCE}
      #TakaoJWT
      JWT_TAKAO_SECRET: ${JWT_TAKAO_SECRET}
      JWT_TAKAO_ISSUER: http://0.0.0.0:8080/
      JWT_TAKAO_AUDIENCE: http://0.0.0.0:8080/audience
      JWT_TAKAO_REALM: ${JWT_TAKAO_REALM}
      JWT_TAKAO_ACCESS_LIFETIME: ${JWT_TAKAO_ACCESS_LIFETIME}
      JWT_TAKAO_REFRESH_LIFETIME: ${JWT_TAKAO_REFRESH_LIFETIME}
      JWT_TAKAO_VERSION: ${JWT_TAKAO_VERSION}
      SERVER_GITHUB_TOKEN: ${SERVER_GITHUB_TOKEN}
volumes:
  db-config: null
  pgadmin-data: null
networks: { }